# Generated by Django 5.0.6 on 2024-07-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0007_course_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата последнего изменения'),
        ),
    ]
