# Generated by Django 5.0.6 on 2024-07-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_verification',
        ),
    ]
