# Generated by Django 5.0.6 on 2024-07-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_payment_datetime_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='datetime_payment',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата оплаты'),
        ),
    ]
