# Generated by Django 5.0.6 on 2024-07-08 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0002_alter_lesson_course'),
        ('userapp', '0006_alter_payment_paid_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='courseapp.lesson'),
        ),
    ]
