# Generated by Django 5.0.6 on 2024-07-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='owner',
        ),
    ]
