# Generated by Django 5.0.6 on 2024-07-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_payment_link_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='сумма оплаты'),
        ),
    ]
