# Generated by Django 5.0.6 on 2024-07-12 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_alter_payment_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cost',
            new_name='price',
        ),
    ]
