# Generated by Django 5.0.6 on 2024-07-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_rename_cost_payment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=' id сессии'),
        ),
    ]
