# Generated by Django 5.0.6 on 2024-07-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_alter_payment_link_alter_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Заходил в последний раз'),
        ),
    ]
